### ISSUE TITLE
Decide if we want Google Custom Search.

### ISSUE THREAD

**Issue by CatalinFrancu** [nerdvana-ro/infoarena#1]
It would be nice to have a [custom Google search](https://programmablesearchengine.google.com/about/). However, Google requires a phone number to set up a new account. Sounds invasive to me. TODO: Decide if we want this.

**Comment by mihaitutu** [comment]
I have modified the code for this to work. I have created a Programmable Search Engine for VArena on Google's services and changed current files for google search views. They had obsolete code which cannot be changed for new installations (Google changed the way their code work). 

Also, modifying a bit of CSS, I was able to hide sponsored ads from the results page. 

Code for g_oogle_search.php_
```
<script async src="https://cse.google.com/cse.js?cx=YOUR_ENGINE_KEY"></script>
<div class="gcse-searchbox-only"></div>
```

Code for _google_search_results.php_
```
<?php include('header.php'); ?>

<h1><?= html_escape($view['title']) ?></h1>  	 
	<div>
		<p>Introduceți numele problemei în câmpul de mai jos. Apoi apăsați butonul de căutare. Va fi afișată o listă cu toate problemele care conțin în titlu sau în textul problemei cuvântul cheie căutat.</p>
	</div>	
		 
	<script async src="https://cse.google.com/cse.js?cx=YOUR_ENGINE_KEY"></script>
	<div class="gcse-searchbox-only"></div>
	<div class="gcse-searchresults-only"></div>
		 
 <?php include('footer.php'); ?>
```
